### ISSUE TITLE
No Win x64 support?

### ISSUE THREAD

**Issue by ryanruby** [samcoe/gh-repo-explore#11]
At least that's what PowerShell 7 tells me

➜ gh extension install https://github.com/samcoe/gh-repo-explore
gh-repo-explore unsupported for windows-amd64. Open an issue: `gh issue create -R samcoe/gh-repo-explore -t'Support windows-amd64'`

**Comment by samcoe** [comment]
I updated the latest release, the naming of the windows binaries did not include the `exe` extension so `gh` failed to recognize that they exist. Can you try again to install the extension?

**Comment by ryanruby** [comment]
Worked, cheers!
